export default {
  banner0: require('./banner/banner1.jpg'),
  banner1: require('./banner/banner1.jpg'),
  banner2: require('./banner/banner1.jpg'),
  book1:require('./books/book_1.jpg'),
  book2:require('./books/book_2.jpg'),
  book3:require('./books/book_3.jpg'),
  book4:require('./books/book_4.jpg'),
  book5:require('./books/book_5.jpg'),
  book6:require('./books/book_6.jpg'),
  book7:require('./books/book_7.jpg'),
  book8:require('./books/book_8.jpg'),
  book9:require('./books/book_9.jpg'),
  book10:require('./books/book_10.jpg'),
  mgz1:require('./mgz/mgz_1.jpg'),
  mgz2:require('./mgz/mgz_2.jpg'),
  mgz3:require('./mgz/mgz_3.jpg'),
  paper1:require('./paper/paper_1.jpg'),
}
